### ISSUE TITLE
It's not possible to buy Bundle Products

### ISSUE THREAD

**Issue by thomaszoeger** [yireo/Yireo_GoogleTagManager2#165] opened 2023-06-20 14:55 UTC
Testsetup 
* Magent 2.4.6-p1 + Sampledata
* Yireo GTM2 verision 3.4.0

Test-procedure
* Creating a bundle product with "Ship Bundle Items" Together, Option Input Type "Checkbox" 
* Add this from product-detail page to basket

Result:
* ?sections=cart.. call responses the following message (ERROR 400)
"The product that was requested doesn&#039;t exist. Verify the product and try again."

without and with disabled GTM2 Extension you can buy the product

**Comment by jissereitsma** [comment] 2023-06-20 17:11
Thanks for addressing this. I've now released 3.4.1 which should fix this issue.

**Comment by thomaszoeger** [comment] 2023-06-20 18:25
I can confirm, it work's now. thank you!

**Comment by jissereitsma** [comment] 2023-06-28 17:21
I'm closing this issue for now. If the problem is still there, feel free to re-open this issue.

**Closed by jissereitsma** 2023-06-28 17:21 UTC
