### ISSUE TITLE
Order information is missing in the datalayer for cart and checkout page.

### ISSUE THREAD

**Issue by nieuwenhuisen** [yireo/Yireo_GoogleTagManager2#28] opened 2018-01-08 12:06 UTC
The datalayer is send to Google tag manager but the order information is missing:

{
customerLoggedIn: 0,
pageType: 'checkout/onepage/success',
gtm: {start: 1512984061563, uniqueEventId: 3},
event: 'gtm.load'
}

The call to /customer/section/load/?sections=yireo-gtm-quote%2Cyireo-gtm-order&_=1515409543661 returns the correct data, but this data is not added to the dataLayer. We use Magento 2.2.1

**Comment by LucScu** [comment] 2018-02-12 08:17
no reply about this issue?

**Comment by jissereitsma** [comment] 2018-02-12 09:02
Sorry for not answering on this. Currently I'm wrapped in a holiday plus picking up lots of voluntary tasks along the way. This issue is not something I have experienced myself. So somebody needs to dive into this - voluntary or paid - but it can't be me for the moment.

**Comment by LucScu** [comment] 2018-02-12 09:07
thx, i try to install on magento 2.2.2 and give a feedback.

**Comment by LucScu** [comment] 2018-02-21 11:33
The issue is that in generic.js all these variables in the getCartSpecificAttributes() method are empty
var cart = customerData.get('cart');
var quote = customerData.get('yireo-gtm-quote');
var order = customerData.get('yireo-gtm-order');

The script try to load data BEFORE they are filled by magento, so they are empty and it can't add it to dataLayer array.

Do you know how to fix it?

**Comment by LucScu** [comment] 2018-02-21 11:41
It is the same issue that customerLoggedIn is always 0 even if customer is logged in.

**Comment by LucScu** [comment] 2018-02-21 17:11
How could be possible that you release a so bugged extension?
If i'm not wrong you trying to access to private data in a wrong mode, [here](http://slides.yireo.com/yireo/m2_private_content) you described it in a different mode.

**Comment by jissereitsma** [comment] 2018-02-21 18:58
@LucScu Please refrain yourself from being nasty. This extension was working earlier without issues, and the issue that you both are having does NOT occur on sites that I'm monitoring. Apparently, you have done something that I haven't anticipated - is that my fault? If you think this extension is crappy, uninstall it and leave us alone. I'm only giving up free time to fix issues that aren't mine, if requests to do so are made in a friendly way. This is not a buggy extension. You have done something to your shop that causes a specific bug to appear and you have not shared that modification in this thread yet.

**Comment by jissereitsma** [comment] 2018-02-21 18:59
@LucScu What is the "mode" that you are referring to?

**Comment by LucScu** [comment] 2018-02-21 20:50
In generic.js there is getCartSpecificAttributes() that try to access to customerData component, when it is not already filled, so cart, quote and order variables are empty and printed to html empty.
I don't know if it is a issue tied to my env (m2.2.2 and 0.3.6), but the same issue is also on @nieuwenhuisen's env.
So, i found [this great tutorial](http://slides.yireo.com/yireo/m2_private_content) and i would ask you why in the tutorial you access to customerData in different mode then this extension (in this extension you don't use uiComponent extension)?
Could you give me a public link to a site that you are monitoring with m2.2.2 so i could see if i have some differences?

**Comment by jissereitsma** [comment] 2018-02-22 04:42
Ok, I assume you are completely aware of how JS components are loaded in Magento using RequireJS and how this lazy loading hooks into the Private Content mechanism, managed by the `customerData` component. Indeed, if data is requested from `customerData` while no other component has inserted things into this yet, the contents will be empty. Hence, it is highly important to make sure that your own JS component (in this case the GTM component) is requesting data, after the other components (for instance, the JS components belonging to the `Magento_Customer` module) has been loaded. Module order is used here, which is again reflected in the RequireJS configuration. In all our environments, this module ordering works fine. In your case, it doesn't.

The tutorial you refer to is written by me. But  nowhere in this tutorial, the word *mode* is used. What is the *mode* that you are referring to? Please explain in technical terms what you see as a major difference between the tutorial and the actual GTM code. They both refer to the same technology, the same principle and the same code. What am I missing, that you think is the core reason why this failing for you, and the reason why we have a discussion on a mysterious word *mode*?

**Comment by LucScu** [comment] 2018-02-22 07:40
Thx @jissereitsma, i just see now 0.3.7, i suddenly install it and test it.
The big difference that i see from this extension and the tutorial is that in tutorial you define foobarComp.js with uiComponent
```
define([
    'uiComponent',
    'Magento_Customer/js/customer-data'
], function (Component, customerData) {
    ...
    return Component.extend({
        initialize: function () {
            this._super();
            this.fooBarComp = customerData.get('fooBarData');
        }
    });
});
```
meanwhile in the extension generic.js is defined without uiComponent
```
define([
    'jquery',
    'underscore',
    'Magento_Customer/js/customer-data'
], function ($, _, customerData) {
    ...
    return {
        'initDataLayer': initDataLayer,
        'monitorSections': monitorSections,
        'monitorCart': monitorCart,
        'monitorCustomer': monitorCustomer,
        'monitorCheckout': monitorCheckout,
        'getCustomer': getCustomer,
        'isLoggedIn': isLoggedIn,
        'getCustomerSpecificAttributes': getCustomerSpecificAttributes,
        'getCartSpecificAttributes': getCartSpecificAttributes,
        'addScriptElement': addScriptElement,
        'yireoGoogleTagManager': function (config) {
            initDataLayer(window);
            monitorSections();

            var attributes = $.extend(getCartSpecificAttributes(), getCustomerSpecificAttributes(), config.attributes);

            if (config.debug) {
                console.log(attributes);
            }

            dataLayer.push(attributes);
            addScriptElement(attributes, window, document, 'script', 'dataLayer', config.id);
        }
    };
});
```
this is what i mean as "different mode" (maybe "different way" is semantically more correct).
Are you agree with my perplexities?

**Comment by jissereitsma** [comment] 2018-02-23 07:29
Ok, I'm sorry to be rude here, but I'm going to cut this discussion short. It seems you have less experience with this kind of thing than I initially thought. There is nothing wrong the overall component architecture and referring to the parent library of a component as *mode* is extremely confusing. Because troubleshooting this requires a thorough understanding of what a JS component is (in Magento terms) and how Magento initializes components in the first place, I can no longer use this thread to discuss this issue with you, unless you provide actual expert clues on what the issue actually is. Your *help* was actually totally off and time-consuming. Instead of answering your questions I might have invested time into the actual problem. So as of yet, the only useful thing in this thread is that there is an issue reported by 2 users and that somebody (with considerable knowledge of the given architecture) needs to invest voluntary time to investigate this. Please do not add any further comments, unless you have brought things to a closer solution - not to a deeper analysis of things that are not note-worthy.

**Comment by LucScu** [comment] 2018-02-23 09:47
Hi, honestly I have no words about your answers.
I installed your 0.3.6 on my m2.2.2, i found a bug, i spent 1 day to discover it and to report here on github.
I read your tutorial and compared to extension to try to help you if i found something wrong.
You don't listen/check my report, but just defense your work and attack me. 
More, yesterday you release a new version 0.3.7 (tested now) that fix the bug reported.
NO WORDS.
I will never report again anything for this extension.
Close the issue.
regards

**Comment by jissereitsma** [comment] 2018-02-23 19:32
Thanks.

**Closed by jissereitsma** 2018-02-23 19:32 UTC
