### ISSUE TITLE
CSP issues on Magento 2.4.7-p2

### ISSUE THREAD

**Issue by dangtrinhtran** [yireo/Yireo_GoogleTagManager2#242] opened 2024-08-15 16:19 UTC
Hi there,

Our system: Magento 2.4.7 + Hyva Theme (not included Hyva Checkout) + One Step Checkout (https://www.onestepcheckout.com/magento-2).

We used to use Magento 2.4.7-p1 with `yireo/magento2-googletagmanager2` version `3.8.3` and got the CSP issues before, and then we applied the patch from https://github.com/yireo/Yireo_GoogleTagManager2/pull/231/file, and the CSP issues were gone and checkout worked fine.

We are upgrading our site to Magento 2.4.7-p2 and `yireo/magento2-googletagmanager2` to `3.9.4`. And now the CSP issues go back on checkout page.

<img width="1848" alt="Screenshot 2024-08-15 at 12 14 53 PM" src="https://github.com/user-attachments/assets/d88f385d-ae0e-4dde-86e7-ccc75634cf44">

Can you guys please help us take a look? What should we do? Should we use the patch above again?

Thank you.

**Comment by jissereitsma** [comment] 2024-08-16 06:56
@dangtrinhtran The patch was merged but totally refactored because it relied on HEREDOC syntax that gave issues with specific Magento versions. However, instead, CSP nonces are implemented in a different way. In other words, version 3.9.4 of this extension should be 100% compatible with CSP.

You are posting errors here. And indeed these are CSP errors. However, the errors do not show that this is due to the Yireo GoogleTagManager2 extension. Inline scripts could be added by other extensions as well. Clicking on the error message its HTML reference brings you to lines 59, 723, 726 and 727. Could you copy and paste those scripts here? Without them, this issue report is not complete.

**Comment by dangtrinhtran** [comment] 2024-08-16 13:37
Hi @jissereitsma 

Thanks for your response. Please see my screenshots when I click on the error messages with lines 59, 723, 726, and 727.


<img width="2251" alt="line_59" src="https://github.com/user-attachments/assets/59d16d73-f386-4994-9f08-66f2e9292419">

<img width="2538" alt="line_723_726_727" src="https://github.com/user-attachments/assets/7dfeaf61-26be-4fcf-b7cd-1e215507ef7c">

**Comment by jissereitsma** [comment] 2024-08-16 13:51
Alright, so it is indeed the Yireo GTM scripts that do not have nonces. However, I'm not able to reproduce this myself - either in various development sites or in various production sites. There seems to be something specific in your own environment.

To help you troubleshoot things, the following DI plugin https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/Plugin/AddCspInlineScripts.php loops through any script to add CSP nonces to it. Perhaps you can debug to see why that plugin is not working for you?

**Comment by dangtrinhtran** [comment] 2024-08-16 15:14
@jissereitsma Thanks for your suggestion. I have no idea for now but looks like this file https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/Util/SecureHtmlRendererStub.php. If I replace the code to `class SecureHtmlRendererStub extends \Magento\Framework\View\Helper\SecureHtmlRenderer {}`
the CSP issues are gone. Do you have any ideas?

**Comment by jissereitsma** [comment] 2024-08-19 07:14
This is very very strange. Which PHP version are you using? Do you know of any changes made to the autoloader of PHP itself? Or some PHP configuration setting related to this?

The issue you are having and the way you can fix it, suggests that either the class `\Magento\Framework\View\Helper\SecureHtmlRenderer` actually is not there, or that the function `class_exists()` somehow behaves differently. 

What if you remove the trailing backslash on line 14:
```php
if (class_exists('Magento\Framework\View\Helper\SecureHtmlRenderer')) {
```

And what if you would use this:
```php
if (class_exists('Magento\Framework\View\Helper\SecureHtmlRenderer::class)) {
```

**Comment by dangtrinhtran** [comment] 2024-08-19 14:42
@jissereitsma I appreciate your help.
I am using PHP 8.3.

> Do you know of any changes made to the autoloader of PHP itself? Or some PHP configuration setting related to this?

If that is the Magento 2 Autoloader, no. That was the default from Magento core.

I also feel very strange about this case but have not been able to find out why.

> What if you remove the trailing backslash on line 14:

`if (class_exists('Magento\Framework\View\Helper\SecureHtmlRenderer')) {`

> And what if you would use this:

`if (class_exists(\Magento\Framework\View\Helper\SecureHtmlRenderer::class)) {`

I tried your suggestions above but no luck. The CSP issues were still there.

**Comment by jissereitsma** [comment] 2024-08-21 11:01
I've done various tests now, but this is still very strange.

To summarize the issue (as I think it is here), the following code doesn't work:
```php
if (class_exists(\Magento\Framework\View\Helper\SecureHtmlRenderer::class)) {
    class SecureHtmlRendererStub extends \Magento\Framework\View\Helper\SecureHtmlRenderer {}
}
```
But the following does work:
```php
class SecureHtmlRendererStub extends \Magento\Framework\View\Helper\SecureHtmlRenderer {}
```

Are you able to duplicate this issue in both production and developer mode? Also, is this something reproduceable in a local development environment (without PHP opcache settings tuned and without the composer autoloader being optimized)?

**Comment by jissereitsma** [comment] 2024-08-21 11:04
Could you also try the following (adding a `false` second parameter to `class_exists`)?
```php
if (class_exists(\Magento\Framework\View\Helper\SecureHtmlRenderer::class, false)) {
    class SecureHtmlRendererStub extends \Magento\Framework\View\Helper\SecureHtmlRenderer {}
}
```

**Comment by hostep** [comment] 2024-08-21 11:25
Is it maybe related to https://github.com/yireo/Yireo_GoogleTagManager2/commit/2c3d0e640726e1a233d1c7b850ce71ca7f74e2ad ?

When working on https://github.com/yireo/Yireo_GoogleTagManager2/pull/239, I think I first tried using the Proxy with xml and for some reason that didn't work, but I can't remember with 100% certainty anymore.

So maybe @dangtrinhtran another way of testing is to try to append `\Proxy` again in the php file like in https://github.com/yireo/Yireo_GoogleTagManager2/pull/239/files and see if that makes it better?

**Comment by jissereitsma** [comment] 2024-08-21 12:16
Just for references, the proxy was moved from code to configuration: https://github.com/yireo/Yireo_GoogleTagManager2/blob/master/etc/frontend/di.xml#L38

**Comment by dangtrinhtran** [comment] 2024-08-22 13:07
> Are you able to duplicate this issue in both production and developer mode? Also, is this something reproduceable in a local development environment (without PHP opcache settings tuned and without the composer autoloader being optimized)?

@jissereitsma Yes, it happened on my local development environment (developer mode) and my server (production mode).

**Comment by jissereitsma** [comment] 2024-08-22 14:21
@hostep I was able to duplicate this my environment after all, so am going to revert those changes. However, I still don't get any of it. As of yet, I'm going to treat the PHP-coded `Proxy` as a necessary evil until we can drop backwards compatibility.

@dangtrinhtran However, your issue is something I have been unable to duplicate so far, and because of that, I don't know a solution either. Could you try upgrading to

**Comment by hostep** [comment] 2024-08-22 15:56
Thanks Jisse, yeah me neither, from my comments in https://github.com/yireo/Yireo_GoogleTagManager2/issues/238#issuecomment-2208546143, if we could figure out why that constructor is called twice, that might already give us some idea about the root cause of the issue.

**Comment by dangtrinhtran** [comment] 2024-08-22 19:39
@jissereitsma I upgraded the module to `3.9.5` and it worked on both modes (developer and production). Thank you for your help.

**Comment by jissereitsma** [comment] 2024-08-26 07:11
Sorry to bring this up again. I already mentioned this towards @hostep in another channel, but the proxy thing sounded nasty to me. Plus I needed to have a proper solution for my other extensions as well. Because of this, I have moved this logic away from the troublesome `SecureHtmlRenderer` and into using the CSP generator directly. This is now in module version 3.9.6 as well - cross fingers that this work ok ...

**Comment by hostep** [comment] 2024-08-26 12:58
Tested with version 3.9.6, and works good for me on my local in production mode 👍, haven't rolled out to a staging environment yet, but I don't expect problems.

**Comment by jissereitsma** [comment] 2024-08-29 14:25
As of yet, this seems to have worked out. I'm closing this issue for now.

**Closed by jissereitsma** 2024-08-29 14:25 UTC

**Comment by dangtrinhtran** [comment] 2024-10-02 16:06
Hi @jissereitsma and @hostep 

I am sorry to bring it back, but just a question.

This is from googletagmanager gtm.js, do you guys have any ideas about this?

<img width="1806" alt="Screenshot 2024-10-02 at 12 01 44 PM" src="https://github.com/user-attachments/assets/8bbcf60d-b60b-4700-9c5b-678553aee5be">

**Comment by jissereitsma** [comment] 2024-10-02 17:33
GTM allows you to add many scripts to your GTM configuration with just a few clicks (including evil scripts). With CSP, every single modification needs to be matched with a custom CSP configuration by the Magento developer (you).

This issue does not seem be related to this Magento extension.

See the following for a proper study: https://www.youtube.com/watch?v=3i8RHLcSAyk

**Comment by dangtrinhtran** [comment] 2024-10-02 17:55
@jissereitsma thanks for sharing it!
