### ISSUE TITLE
Magento_Checkout: "logger not defined" after disabled tracking setting in config (affected : all versions v3.3.2+)

### ISSUE THREAD

**Issue by bonanzadigger** [yireo/Yireo_GoogleTagManager2#167] opened 2023-06-22 12:43 UTC
Hi,
the following combination leads to a blocking javascript-error in frontend of Magento Checkout:

config.php:
**'Yireo_GoogleTagManager2' => 1**

env.php:
'googletagmanager2' => [
   'settings' => [
      .....
      **'enabled' => '0'**,                  
    ]
  ],

Affetcted Yireo Googletagmanager versions: 3.3.2+

The issue is caused by:
vendor/yireo/magento2-googletagmanager2/view/frontend/web/js/mixins/step-navigator-mixin.js

In that file "logger" is missing. Should be injected I guess?

**Comment by jissereitsma** [comment] 2023-06-28 17:21
I'm closing this issue for now. If the problem is still there, feel free to re-open this issue.

**Closed by jissereitsma** 2023-06-28 17:21 UTC
