### ISSUE TITLE
Error when deleting product from cart

### ISSUE THREAD

**Issue by web4exposure-org** [yireo/Yireo_GoogleTagManager2#201] opened 2023-12-12 13:33 UTC
When I want to remove a product from the cart (or set the amount of one product to zero) I get the following error:

main.CRITICAL: RuntimeException: Using getProducts() before setProductSkus() in /var/www/html/vendor/yireo/magento2-googletagmanager2/Util/ProductProvider.php:49
Stack trace:
#0 /var/www/html/vendor/yireo/magento2-googletagmanager2/Util/ProductProvider.php(66): Yireo\GoogleTagManager2\Util\ProductProvider->getProducts()
#1 /var/www/html/vendor/yireo/magento2-googletagmanager2/DataLayer/Mapper/CartItemDataMapper.php(47): Yireo\GoogleTagManager2\Util\ProductProvider->getBySku('50004173')
#2 /var/www/html/vendor/yireo/magento2-googletagmanager2/DataLayer/Event/RemoveFromCart.php(27): Yireo\GoogleTagManager2\DataLayer\Mapper\CartItemDataMapper->mapByCartItem(Object(Magento\Quote\Model\Quote\Item\Interceptor))
#3 /var/www/html/vendor/yireo/magento2-googletagmanager2/Observer/TriggerRemoveFromCartDataLayerEvent.php(30): Yireo\GoogleTagManager2\DataLayer\Event\RemoveFromCart->get()
#4 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Yireo\GoogleTagManager2\Observer\TriggerRemoveFromCartDataLayerEvent->execute(Object(Magento\Framework\Event\Observer))
#5 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Yireo\GoogleTagManager2\Observer\TriggerRemoveFromCartDataLayerEvent), Object(Magento\Framework\Event\Observer))
#6 /var/www/html/vendor/magento/framework/Event/Manager.php(65): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#7 /var/www/html/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('sales_quote_rem...', Array)
#8 /var/www/html/vendor/magento/module-quote/Model/Quote.php(1576): Magento\Framework\Event\Manager\Proxy->dispatch('sales_quote_rem...', Array)
#9 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Quote\Model\Quote->removeItem(109134)
#10 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Quote\Model\Quote\Interceptor->___callParent('removeItem', Array)
#11 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Quote\Model\Quote\Interceptor->Magento\Framework\Interception\{closure}(109134)
#12 /var/www/html/generated/code/Magento/Quote/Model/Quote/Interceptor.php(41): Magento\Quote\Model\Quote\Interceptor->___callPlugins('removeItem', Array, Array)
#13 /var/www/html/vendor/magento/module-checkout/Model/Cart.php(579): Magento\Quote\Model\Quote\Interceptor->removeItem(109134)
......

I'm using magento 2.4.6-p3 and the newest version of the hyva theme.

**Comment by jissereitsma** [comment] 2023-12-12 15:07
Thanks Web4Exposure (are you a real person? :)) This should now be fixed in version 3.7.1.

**Comment by web4exposure-org** [comment] 2023-12-12 15:33
Yes I'm Dennis, a real person, using our company account :)
Thanks!

**Comment by jissereitsma** [comment] 2023-12-12 16:00
Gotcha, Dennis :) I also prefer to keep things the way that GitHub wants them - regular accounts for regular people, organizations for companies. Anyway, let me know if the problem is fixed. If so, we can close this issue.

**Closed** 2023-12-13 10:40 UTC
