### ISSUE TITLE
The module breaks the sort functionality in Magento 2.4

### ISSUE THREAD

**Issue by onepack** [yireo/Yireo_GoogleTagManager2#70] opened 2020-08-28 19:06 UTC
Last week a customer upgraded to M 2.4. They also use Yireo - GTM 2.0.1 with Magento.
We noticed that the Yireo module would break all sorting options in the category grids in M2.4.
Once the module is activated all sorting options are ignored and only the sort order by id (latest) is used.

**Comment by onepack** [comment] 2020-08-28 20:52
For now I disabled line 182 and 183 from vendor/yireo/magento2-googletagmanager2/ViewModel/Script.php
`//        $categoryBlock->setCategory($currentCategory);
//        $childScript .= $categoryBlock->toHtml();`

After this the sort started working again.
It's a bit drastic but a quick fix for now to get things working again.
I will check for a proper fix later in the weekend.

**Comment by jissereitsma** [comment] 2020-08-29 10:31
Thanks for reporting this. I have tested this with a clean Magento 2.4.0 environment and Yireo GoogleTagManager 2.0.1. Unfortunately, I don't see any issues here. First, I have tested that sorting using the **Sort By** widget on a category page works, without the GTM extension being enabled. This works. Next, I have enabled the GTM extension. It still works.

I would be also hugely confused how the script that simply adds output to the page would suddenly "break" things. But perhaps you could explain what *break* means? Is it a JavaScript error? Is it a PHP error? Is it a log somewhere?

**Comment by onepack** [comment] 2020-08-29 11:32
Hi Jisse,

I'm as confused as you are. It took me two full days of testing to find the source of the sorting issue.
After the shop was upgraded to 2.4 all seemed ok except for the category product order.

The products seemed to just show in a not logic order. A fixed order.
Sorting acs/desc made no difference, product A would be number one and stay there.
Choosing price as the sort option also did not do anything to the order. The same with Sku and Name.

Checking the backend "category: products in grid" setting showed that the frontend order was the same as the products order by id in the category grid. (newest first).

I managed to work away some javascript errors but they were not related to this.
The thing is that the issue was persistent after I changed the theme to be "blank".
and even after I disabled all external modules like Amasty/ Mirasvit, Multisafepay and my own.

It was only after I disabled the Yireo GTM module that things started working again.
I checked this two times by enabling all modules except Yireo GTM and all stayed good.
Enabling this Yireo module again and the sort was broken (without php errors or js errors).

I will check if the error is due to a module conflict with Amasty layered navigation or Mirasvit Search Ultimate.

Will keep you updated.

**Comment by pauldonnelly** [comment] 2020-10-28 02:16
Hi Jissie,

I can confirm this issue as well on M 2.4.1 (migrated from 1.9.2.4). 

For me it started with the product listing showing all products and ignoring the pagination limits (12,24,26). I then noticed the Sort By options did nothing, it didn't change anything on the page it just refreshed. I disabled all modules installed except Yireo_GoogleTagManager2 and a Blog module which i assumed would have no impact on product listings. The issue was still present so I disabled all modules including yours and one by one started adding then again. Yireo_GoogleTagManager2 was the last module I enabled and then issue appeared again.

I then disabled all modules except Yireo_GoogleTagManager2 and the issue was still there.

**Comment by jissereitsma** [comment] 2020-10-28 10:28
It took some effort, but I was able to reproduce this (with a specific module ordering, not a blank installation) and then work on a fix. Apparently, the block ordering happened in such way that the GTM block was loading earlier than the category block itself, and therefore the GTM extension was "resetting" part of the collection loading. I've now refactored this entire logic so that there is a real dependency upon the original category block. 

This is now released in version 2.0.2. Could you see if this fixed things for you?

**Comment by pauldonnelly** [comment] 2020-10-28 11:28
Thanks Jisse. I can confirm this has fixed the issue.
Pagination is working correctly and Sort By is now sorting as it should.
Great work, thank you.

**Comment by onepack** [comment] 2021-01-21 00:29
I'm afraid I had to adjust the module again with the same changes as before. ( commented on Aug 28, 2020)
After I upgraded the same client to version 2.4.1 the whole category page appeared empty except some part of the toolbar and one select item in the sort.
After some digging this same issue seemed to be causing the whole category page not to appear.

**Comment by jissereitsma** [comment] 2021-01-27 06:38
Thanks for letting us know. I've done testing myself as well, but can't confirm this. I've tested GoogleTagManager2 version 2.0.3 with Magento 2.4.1, with both caching disabled (block, full page, XML layout) and enabled. But in all cases it is working perfectly fine.

You mention that the whole category page did not appear. You mean there was a blank page (which suggests a fatal error)? Or a blank content area? Or a category area, but no products in it? Also, was this tested with caching on / off? Production mode or developer mode? Varnish or no Varnish?

**Comment by onepack** [comment] 2021-02-02 15:46
Hi Jisse,

This is what I get on Dev and Prod:
![example-broken-cat](https://user-images.githubusercontent.com/475598/106622243-b0fdce80-6573-11eb-932f-e6714a518f2a.png)

The page loads and then breaks at the sort and stops loading the content. In the source there is only 
the head
toolbar html
Js in Footer

I disabled the custom theme on the DEV environment and tried with the blank theme and still all seems broken on the Category pages.
Redis cache is not enabled on the DEV.

There is no option for me other than putting back the previous fix in order to make things work.

**Comment by jissereitsma** [comment] 2021-02-03 06:12
Thanks for reporting. Unfortunately, in none of my testing sites or customer sites this is popping up. So please note that this is not a generic issue with the extension. But it is related to something specifically done in your shop. And without the details to specify that, everyone will be wildly guessing here.

If you say that something stops loading and things break, then there should be the possibility of getting a technical error from this. Likewise, you have proven that the theme is not involved here. But what about modules? My guess is that you have installed another module that is trying to override the exact same page, which is why this is causing an issue.

**Comment by onepack** [comment] 2021-02-03 15:05
I agree with you that there must be a conflict but the logs remain empty.
Will come back on this when I have more info.

**Comment by thioz** [comment] 2021-07-02 08:45
Hi Jisse, 

I am having the same problems with the 2.0.5 version in Magento 2.4.2  as @onepack  describes and have have found where it happens and how to stop it from happening.

In : Yireo\GoogleTagManager2\Block\Category 
method : getLoadedProductCollection
Line 44 : $productListBlock->toHtml();

if this line is removed or commented the page will display as normal. 

I also don't see any reason to render the productListBlock in this class 

Kind regards 

Rob Theeuwes - Accent Interactive

**Comment by jissereitsma** [comment] 2021-07-02 15:41
Thanks. Could you do a listing of all third party plugins that are overloading Blocks on the mentioned page? Because this is not something that occurs in any combination of core extension, it must be due to a combination with third party extensions.

**Comment by thioz** [comment] 2021-07-05 06:32
@jissereitsma 

There are quite a lot of third party plugins installed, but I still don't see the need to render the product list block without actually doing anything with the result. 

for now I will override the block to get it working.

**Comment by jissereitsma** [comment] 2021-07-09 17:05
@thioz That's where the code should explain things. You say that the code is not doing anything, but if you would remove the entire category block of this GTM module and you would move the GTM block to the top of the body, then all products will be gone from the GTM result. And because it is best-practice to load the GTM block right after the opening body tag, this is quite an issue. I hope we can agree upon that.

But the point is take, the block call is causing other modules to break, most likely because they are extending from the original category block (instead of dealing with things like ViewModels, plugins, types, etc).

I will see if there is a better way of detecting which products are being loaded by the product listing block, before the product listing block is loaded. (The definition of this sentence should point into why this is quite hard.)

Still, you complained about the current behaviour of this module, but you didn't give feedback on why this is causing an issue on your specific site, while it is working on 100s of other sites without issues. I would say that this is related to another third party extension. Which one(s)?

**Comment by jissereitsma** [comment] 2021-07-11 10:30
I've added version 2.1.0 with a complete refactoring of the code. Could you see if this works for you?

**Comment by thioz** [comment] 2021-07-12 07:30
@jissereitsma After some digging I found that our customer also uses Anowave Google Tag Manager Enhanced and I think that is where the collision happens. 

I will try out the new version today and see what happens. 

thanks

**Comment by jissereitsma** [comment] 2021-07-12 10:19
I would definitely recommend never to install two modules that do the same thing. So disable the one and keep the other.

**Comment by pinja-juusohanhivaara** [comment] 2021-11-12 11:05
> @jissereitsma After some digging I found that our customer also uses Anowave Google Tag Manager Enhanced and I think that is where the collision happens.
> 
> I will try out the new version today and see what happens.
> 
> thanks

I had a similar issue with Anowave GTM module. Which got fixed by going to admin store config and Changing
Anowave -> Google tag manager -> Enhanced Ecommerce Tracking preferences  -> "Impresson payload model"
to "Set dataLayer[] impressions after Pageview (requires additional tag/trigger)"

**Comment by justenpeters** [comment] 2021-11-16 18:36
@jissereitsma just wanted to comment that I was having this issue on 2.4.2 with a previous version of the module, but updating to 2.1.3 resolved the issue.

**Comment by jissereitsma** [comment] 2021-11-17 06:16
@justenpeters Thanks for this feedback.

I'm closing this issue for now. The issue seemed to have been solved with 2.1.0 or higher. And if somebody is using this Yireo GTM plus Anowave GTM, somebody needs to explain me how duplicate data submission is prevented.

**Closed by jissereitsma** 2021-11-17 06:16 UTC
