### ISSUE TITLE
Template for select item is never included in Category pages

### ISSUE THREAD

**Issue by TheBadong** [yireo/Yireo_GoogleTagManager2#250] opened 2024-10-11 09:28 UTC
Hello!

While trying to add some data to the Select Item event, I noticed the base data is always empty (contains only the product id). I see that the template `view/frontend/templates/product/details.phtml` never gets included on the category view page layout. Any idea why this might be happening? It seems like it should be there given the layout file `view/frontend/layout/catalog_category_view.xml` (the module is well enabled).

Module version 3.9.8
Adobe Commerce 2.4.4-p10

**Comment by jissereitsma** [comment] 2024-11-12 07:41
If you would inspect the XML layout closer, you can see that the block `yireo_googletagmanager2.product-details.inner` is defined in the body but never added to another block or container. So indeed, it never appears.

However, the intention is that it was actually added through a DI plugin `Plugin/AddProductDetails.php` automatically. But then again, the XML layout names do not match anymore. And this again was caused by some refactoring gone bad.

I've now renamed the layout name in the next release, so it matches again. This should fix things for the basic data. (As a note, under Hyvä things were still working.)

Thanks for spotting this!

**Comment by jissereitsma** [comment] 2024-11-16 07:59
I assume that this has been fixed now and will close this issue. If the problem is still there, let me know and we'll reopen this ticket.

**Closed by jissereitsma** 2024-11-16 07:59 UTC
